# Generated by Django 5.0.1 on 2024-08-18 16:11

import django.db.models.deletion
import django.utils.timezone
import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor_Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=255, null=True)),
                ('update_ms', models.IntegerField()),
                ('params', models.JSONField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Configuration',
            },
        ),
        migrations.CreateModel(
            name='Sensor_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Sensor Type',
            },
        ),
        migrations.CreateModel(
            name='Data_PZEM004t',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(default=django.utils.timezone.now, interval='1 day')),
                ('sensor_address', models.PositiveSmallIntegerField()),
                ('volts', models.PositiveSmallIntegerField()),
                ('amps', models.DecimalField(decimal_places=2, max_digits=5)),
                ('frequency', models.PositiveSmallIntegerField()),
                ('watts', models.DecimalField(decimal_places=2, max_digits=6)),
                ('energy', models.DecimalField(decimal_places=2, max_digits=6)),
                ('power_factor', models.PositiveSmallIntegerField()),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.sensor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_configuration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensors.sensor_configuration'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sensors.sensor_type'),
        ),
    ]
