# Generated by Django 4.2 on 2023-05-05 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor_Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=255, null=True)),
                ('update_ms', models.IntegerField()),
                ('params', models.JSONField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('sensor_configuration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensors.sensor_configuration')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sensors.sensor_type')),
            ],
        ),
    ]
