# Generated by Django 4.2.1 on 2023-05-26 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(null=True)),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sensors.sensor')),
            ],
        ),
    ]
