# Generated by Django 5.0.1 on 2026-04-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='data_pzem004t',
            index=models.Index(fields=['sensor_id', '-time'], name='data_pzem004t_sensor_time_idx'),
        ),
    ]
