# Generated by Django 4.2 on 2023-04-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_data_delete_sensor_data_rename_reference_sensor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
