# Generated by Django 4.2 on 2023-04-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_alter_data_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_configuration',
            name='params',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sensor_type',
            name='type',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
