# Generated by Django 4.2 on 2023-04-24 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_alter_sensor_configuration_params_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sensors.sensor_configuration'),
        ),
    ]
