# Generated by Django 4.2 on 2023-04-24 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_alter_sensor_sensor_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor_configuration',
            name='description',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_configuration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sensors.sensor_configuration'),
        ),
    ]
