# Generated by Django 4.2 on 2023-04-24 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_sensor_configuration_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor_configuration',
            old_name='update_interval',
            new_name='update_interval_ms',
        ),
    ]
