# Generated by Django 4.2 on 2023-04-24 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_rename_update_interval_sensor_configuration_update_interval_ms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor_configuration',
            old_name='update_interval_ms',
            new_name='update_ms',
        ),
    ]
