# Generated by Django 5.0.1 on 2024-08-18 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Received',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(null=True)),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sensors.sensor')),
            ],
        ),
    ]
