# Generated by Django 5.0.1 on 2026-04-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqttclient', '0001_initial'),
        ('sensors', '0002_data_pzem004t_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='data_received',
            index=models.Index(fields=['sensor_id', '-time'], name='data_received_sensor_time_idx'),
        ),
    ]
