# Generated by Django 4.2.1 on 2023-05-26 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqttclient', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
